import CryptoKit
import Foundation

/// A locally generated, non-authority challenge for checking retention of the
/// already-registered Site Root ACK private key across an in-place update.
///
/// The challenge is never derived from an imported file or host response. The
/// signature is ephemeral, has no submission method, and cannot authorise a
/// Site Root operation.
struct SiteRootAckContinuityProbeV1: Equatable, Sendable {
  static let domain = Data("mnemosyne.pistis.site-root-ack-continuity.v1\0".utf8)

  let siteUUID: String
  let generation: UInt64
  let nonce: Data
  let message: Data

  init(siteUUID: String, generation: UInt64, nonce: Data) throws {
    guard let uuid = SiteRootConvergenceEncoding.uuidBytes(siteUUID),
      generation > 0, nonce.count == 32, !nonce.allSatisfy({ $0 == 0 })
    else { throw PlatformFailure.invalidConfiguration }
    var generationBytes = Data()
    for shift in stride(from: 56, through: 0, by: -8) {
      generationBytes.append(UInt8(truncatingIfNeeded: generation >> UInt64(shift)))
    }
    self.siteUUID = siteUUID
    self.generation = generation
    self.nonce = nonce
    message = Self.domain + uuid + generationBytes + nonce
  }

  /// Makes a fresh nonce with the system random-number generator.
  static func generate(siteUUID: String, generation: UInt64) throws -> Self {
    var generator = SystemRandomNumberGenerator()
    let nonce = Data((0..<32).map { _ in UInt8.random(in: .min ... .max, using: &generator) })
    return try Self(siteUUID: siteUUID, generation: generation, nonce: nonce)
  }

  /// Verifies the post-update signature against the exact public key and
  /// generation retained before the update.
  func verify(signature: Data, preUpdatePublicKey: Data, preUpdateGeneration: UInt64) -> Bool {
    guard preUpdateGeneration == generation,
      let publicKey = try? P256.Signing.PublicKey(
        compressedRepresentation: preUpdatePublicKey
      ),
      let rawSignature = try? P256.Signing.ECDSASignature(
        rawRepresentation: signature
      )
    else { return false }
    return publicKey.isValidSignature(rawSignature, for: message)
  }

  /// Signs only the challenge generated by this value. A production caller
  /// supplies the existing key's Face ID-gated Secure Enclave operation.
  func sign(
    using existingKey: (Data) throws -> Data,
    preUpdatePublicKey: Data,
    preUpdateGeneration: UInt64
  ) throws -> Data {
    guard preUpdateGeneration == generation else {
      throw PlatformFailure.siteRootAuthorityUnavailable
    }
    let signature = try existingKey(message)
    guard
      verify(
        signature: signature,
        preUpdatePublicKey: preUpdatePublicKey,
        preUpdateGeneration: preUpdateGeneration
      )
    else { throw PlatformFailure.malformedSignature }
    return signature
  }
}
