use crate::{
    BindingExpectation, BindingResolver, DeliveryProfile, Generation, IntegrationBlocker,
    OperationPurpose, StandaloneReadiness,
};
use pistis_domain::{DeviceId, InstallationId, KeyId, UserId};
use pistis_identity::BindingId;
use pistis_protocol::UnixTimeMillis;

/// Independent non-secret identifier correlating completion and audit.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct AuditCorrelationId([u8; 16]);

impl AuditCorrelationId {
    /// Constructs an identifier from independently generated bytes.
    #[must_use]
    pub const fn from_bytes(bytes: [u8; 16]) -> Self {
        Self(bytes)
    }

    /// Returns the opaque bytes.
    #[must_use]
    pub const fn as_bytes(&self) -> &[u8; 16] {
        &self.0
    }

    /// Returns whether this is the reserved all-zero sentinel.
    ///
    /// A host completion must reject this value before it resolves bindings or
    /// requests a session. Correlation identifiers are independently generated
    /// audit metadata, never an optional/default field.
    #[must_use]
    pub fn is_zero_sentinel(&self) -> bool {
        self.0 == [0; 16]
    }
}

/// Digest of a host session identifier, never the session credential.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SessionIdDigest([u8; 32]);

impl SessionIdDigest {
    /// Constructs an audit-safe digest supplied by Prosopikon.
    #[must_use]
    pub const fn from_bytes(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }

    /// Returns the digest bytes.
    #[must_use]
    pub const fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }
}

/// Request to Prosopikon, Monas's sole browser-session authority.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct HostSessionRequest {
    /// Existing immutable Prosopikon principal.
    pub principal_id: UserId,
    /// Installation accepting authentication.
    pub installation_id: InstallationId,
    /// Device that authenticated.
    pub device_id: DeviceId,
    /// Exact verification key used.
    pub key_id: KeyId,
    /// External identity binding slot.
    pub binding_id: BindingId,
    /// Authoritative authentication time.
    pub authenticated_at: UnixTimeMillis,
    /// Current policy generation.
    pub policy_generation: Generation,
    /// Current revocation generation.
    pub revocation_generation: Generation,
    /// Independent audit correlation identifier.
    pub correlation_id: AuditCorrelationId,
    /// Closed operation purpose; always ordinary session authentication.
    pub purpose: OperationPurpose,
}

impl HostSessionRequest {
    /// Authorizes a request only for the ready standalone profile and current bindings.
    ///
    /// The host invokes its issuer inside the transaction that consumes the
    /// challenge, invalidates pre-authentication state, requests the session,
    /// and appends audit evidence.
    ///
    /// # Errors
    ///
    /// A non-standalone profile, missing evidence, or binding failure blocks
    /// the request before any host mutation.
    pub fn authorize(
        profile: DeliveryProfile,
        readiness: &StandaloneReadiness,
        resolver: &impl BindingResolver,
        expected: BindingExpectation,
        authenticated_at: UnixTimeMillis,
        correlation_id: AuditCorrelationId,
    ) -> Result<Self, IntegrationBlocker> {
        if profile != DeliveryProfile::Standalone {
            return Err(IntegrationBlocker::WrongProfile(profile));
        }
        readiness.require_ready()?;
        if correlation_id.is_zero_sentinel() {
            return Err(IntegrationBlocker::InvalidAuditCorrelation);
        }
        let binding = resolver
            .resolve(expected)
            .map_err(IntegrationBlocker::Binding)?;
        binding
            .validate(expected)
            .map_err(IntegrationBlocker::Binding)?;
        Ok(Self {
            principal_id: binding.principal_id,
            installation_id: binding.installation_id,
            device_id: binding.device_id,
            key_id: binding.key_id,
            binding_id: binding.binding_id,
            authenticated_at,
            policy_generation: binding.policy_generation,
            revocation_generation: binding.revocation_generation,
            correlation_id,
            purpose: expected.purpose,
        })
    }
}

/// Outcome from Prosopikon's normal browser-session authority.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct HostSessionOutcome {
    /// Audit-safe digest of the issued session identifier.
    pub session_id_digest: SessionIdDigest,
    /// Absolute session expiry.
    pub expires_at: UnixTimeMillis,
}

/// Prosopikon session issuance boundary implemented by the host.
pub trait HostSessionIssuer {
    /// Requests a normal host session within atomic completion.
    ///
    /// No raw token, cookie, role, or product authorization crosses this port.
    ///
    /// # Errors
    ///
    /// Any issuance, audit, or transaction failure rolls back completion.
    fn issue(&self, request: HostSessionRequest) -> Result<HostSessionOutcome, HostSessionError>;
}

/// Coarse host-session failure safe across the adapter boundary.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum HostSessionError {
    /// Host persistence or session authority is unavailable.
    Unavailable,
    /// Transactional completion conflicted with concurrent state.
    Conflict,
    /// Transactional audit append failed.
    AuditFailed,
}
