//! Fail-closed iPhone-attested Site Trust human-authority facts.
//!
//! This is a framework-neutral Pistis-to-Monas contract.  It binds an
//! iPhone-attestation verification request to the exact non-secret Proxenos
//! canonical payload and opaque Pistis intent.  It deliberately does not
//! provide an Apple verifier, HTTP route, browser session, local account, or
//! persistence implementation.  Monas owns the durable transaction through
//! [`SiteTrustFactStoreV1`].

use core::fmt;

use pistis_domain::{DeviceId, InstallationId, KeyId};
use pistis_protocol::UnixTimeMillis;
use sha2::{Digest as _, Sha256};

mod issuance;

pub(crate) use issuance::{
    build_site_trust_human_authority_fact_from_verified_v1,
    issue_site_trust_human_authority_fact_from_verified_v1,
};

/// Exact versioned profile for the durable human-authority fact.
pub const SITE_TRUST_HUMAN_AUTHORITY_FACT_PROFILE_V1: &str =
    "mnemosyne.pistis.site-trust-human-authority-fact.v1";

const PROXENOS_PAYLOAD_PROFILE_V1: &str = "mnemosyne.proxenos.std.v1";
const PISTIS_INTENT_PREFIX_V1: &str = "mnemosyne.pistis.intent.v1:";
const FACT_ID_DOMAIN_V1: &[u8] = b"mnemosyne.pistis.site-trust-fact-id.v1\0";
const ATTESTATION_CHALLENGE_DOMAIN_V1: &[u8] =
    b"mnemosyne.pistis.site-trust-app-attest-challenge.v1\0";
const FACT_PAYLOAD_FIELDS: usize = 13;
const MAXIMUM_PAYLOAD_FIELD_BYTES: usize = 128;
const MAXIMUM_ASSERTION_BYTES: usize = 16 * 1024;
const MAXIMUM_INTENT_BYTES: usize = 192;

/// A fixed one-use iPhone ceremony identifier.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct SiteTrustFactCeremonyIdV1([u8; 16]);

impl SiteTrustFactCeremonyIdV1 {
    /// Creates a non-secret ceremony identifier from independently generated bytes.
    #[must_use]
    pub const fn from_bytes(bytes: [u8; 16]) -> Self {
        Self(bytes)
    }

    /// Returns the opaque ceremony bytes for a host-owned durable store.
    #[must_use]
    pub const fn as_bytes(&self) -> &[u8; 16] {
        &self.0
    }

    /// Returns whether this is the forbidden all-zero sentinel.
    #[must_use]
    pub fn is_zero_sentinel(self) -> bool {
        self.0 == [0; 16]
    }
}

/// A SHA-256 digest binding an App Attest assertion to one ceremony request.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SiteTrustAttestationChallengeDigestV1([u8; 32]);

impl SiteTrustAttestationChallengeDigestV1 {
    /// Returns the exact digest bytes which the Apple verifier must validate.
    #[must_use]
    pub const fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }
}

/// A stable, audit-safe identifier for one verified human-authority fact.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct SiteTrustFactIdV1([u8; 32]);

impl SiteTrustFactIdV1 {
    /// Returns the opaque deterministic fact identifier bytes.
    #[must_use]
    pub const fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }
}

/// Structural failure when parsing a Proxenos canonical Site Trust payload.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SiteTrustCanonicalPayloadErrorV1 {
    /// The payload is truncated, oversized, reordered, or contains extra data.
    NonCanonical,
    /// A payload value is not printable ASCII or has an invalid length.
    InvalidField,
    /// The exact Proxenos profile or v1 version is absent.
    WrongProfile,
    /// The payload is not a pending ceremony request.
    WrongState,
    /// The audience or purpose is outside the closed Proxenos v1 set.
    UnsupportedAudienceOrPurpose,
    /// The payload attempts to carry authority material that cannot cross this boundary.
    ProhibitedMaterial,
    /// The opaque intent reference is malformed.
    InvalidIntentReference,
}

impl fmt::Display for SiteTrustCanonicalPayloadErrorV1 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::NonCanonical => "Site Trust canonical payload is invalid",
            Self::InvalidField => "Site Trust canonical payload field is invalid",
            Self::WrongProfile => "Site Trust canonical payload profile is invalid",
            Self::WrongState => "Site Trust canonical payload state is invalid",
            Self::UnsupportedAudienceOrPurpose => "Site Trust audience or purpose is unsupported",
            Self::ProhibitedMaterial => "Site Trust payload crosses prohibited material",
            Self::InvalidIntentReference => "Site Trust intent reference is invalid",
        })
    }
}

impl std::error::Error for SiteTrustCanonicalPayloadErrorV1 {}

/// Exact parsed non-secret Proxenos Site Trust payload bytes.
///
/// Proxenos remains the final authority that validates the complete payload
/// against its active Site Trust state.  This type only accepts the frozen v1
/// canonical grammar so Pistis can bind the exact bytes to human intent.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SiteTrustCanonicalPayloadV1 {
    canonical_bytes: Vec<u8>,
    digest: [u8; 32],
    site_id: String,
    audience: String,
    purpose: String,
    intent_reference: String,
}

impl SiteTrustCanonicalPayloadV1 {
    /// Parses exactly one frozen 13-field Proxenos v1 TLV payload.
    ///
    /// # Errors
    ///
    /// Returns a redacted structural failure without retaining raw input in
    /// the error.  It never validates a detached Site Trust proof.
    pub fn parse(canonical_bytes: Vec<u8>) -> Result<Self, SiteTrustCanonicalPayloadErrorV1> {
        let values = parse_payload_fields(&canonical_bytes)?;
        if values[0] != PROXENOS_PAYLOAD_PROFILE_V1 || values[1] != "1" {
            return Err(SiteTrustCanonicalPayloadErrorV1::WrongProfile);
        }
        if values[2] != "request-pending" {
            return Err(SiteTrustCanonicalPayloadErrorV1::WrongState);
        }
        if !matches!(
            values[7].as_str(),
            "monas-local"
                | "oikodome-local"
                | "dasobjectstore-local"
                | "phoreus-registry-local"
                | "phoreus-forge-local"
                | "jenkins-local"
        ) || !matches!(
            values[8].as_str(),
            "trust-observe" | "trust-admission" | "trust-deploy" | "trust-execute"
        ) {
            return Err(SiteTrustCanonicalPayloadErrorV1::UnsupportedAudienceOrPurpose);
        }
        if values
            .iter()
            .any(|value| contains_prohibited_material(value))
        {
            return Err(SiteTrustCanonicalPayloadErrorV1::ProhibitedMaterial);
        }
        if !valid_intent_reference(&values[12]) {
            return Err(SiteTrustCanonicalPayloadErrorV1::InvalidIntentReference);
        }
        Ok(Self {
            digest: Sha256::digest(&canonical_bytes).into(),
            canonical_bytes,
            site_id: values[3].clone(),
            audience: values[7].clone(),
            purpose: values[8].clone(),
            intent_reference: values[12].clone(),
        })
    }

    /// Returns the exact bytes which must be forwarded unchanged to Proxenos.
    #[must_use]
    pub fn canonical_bytes(&self) -> &[u8] {
        &self.canonical_bytes
    }

    /// Returns the SHA-256 digest of the exact canonical bytes.
    #[must_use]
    pub const fn digest(&self) -> &[u8; 32] {
        &self.digest
    }

    /// Returns the canonical payload's non-secret Site Trust identifier.
    #[must_use]
    pub fn site_id(&self) -> &str {
        &self.site_id
    }

    /// Returns the exact closed product audience.
    #[must_use]
    pub fn audience(&self) -> &str {
        &self.audience
    }

    /// Returns the exact closed Site Trust purpose.
    #[must_use]
    pub fn purpose(&self) -> &str {
        &self.purpose
    }

    /// Returns the opaque field-13 Pistis intent evidence reference.
    #[must_use]
    pub fn intent_reference(&self) -> &str {
        &self.intent_reference
    }
}

/// A bounded raw App Attest assertion accepted only as untrusted verifier input.
///
/// This value is never stored in a human-authority fact, returned to Monas, or
/// emitted in an error.  It is retained only for the synchronous verifier call.
#[derive(Clone, Eq, PartialEq)]
pub struct AppleAppAttestAssertionV1(Vec<u8>);

impl fmt::Debug for AppleAppAttestAssertionV1 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("AppleAppAttestAssertionV1")
            .field("byte_len", &self.0.len())
            .finish()
    }
}

impl AppleAppAttestAssertionV1 {
    /// Bounds untrusted assertion bytes before they reach an Apple verifier.
    ///
    /// # Errors
    ///
    /// Returns a redacted verification failure for empty or oversized input.
    pub fn parse(bytes: Vec<u8>) -> Result<Self, AttestationVerificationFailureV1> {
        if bytes.is_empty() || bytes.len() > MAXIMUM_ASSERTION_BYTES {
            return Err(AttestationVerificationFailureV1::Invalid);
        }
        Ok(Self(bytes))
    }

    /// Returns bounded assertion bytes only to sibling Pistis verification
    /// boundaries.  They must remain transient and must never be retained in a
    /// fact, vector, error, or transport response.
    #[must_use]
    pub(crate) fn transient_bytes(&self) -> &[u8] {
        &self.0
    }
}

/// A versioned opaque Pistis intent binding required by the Proxenos UDS profile.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SiteTrustPistisIntentV1(String);

impl SiteTrustPistisIntentV1 {
    /// Parses one exact `mnemosyne.pistis.intent.v1:` intent reference.
    ///
    /// # Errors
    ///
    /// Returns a redacted failure for an unknown, oversized, or non-canonical intent.
    pub fn parse(value: String) -> Result<Self, SiteTrustCanonicalPayloadErrorV1> {
        let Some(reference) = value.strip_prefix(PISTIS_INTENT_PREFIX_V1) else {
            return Err(SiteTrustCanonicalPayloadErrorV1::InvalidIntentReference);
        };
        if value.len() > MAXIMUM_INTENT_BYTES || !valid_intent_reference(reference) {
            return Err(SiteTrustCanonicalPayloadErrorV1::InvalidIntentReference);
        }
        Ok(Self(value))
    }

    /// Returns the exact wire value accepted by Proxenos.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }

    fn reference(&self) -> &str {
        self.0
            .strip_prefix(PISTIS_INTENT_PREFIX_V1)
            .expect("validated Site Trust intent prefix")
    }
}

/// The exact non-secret request that an Apple App Attest verifier must bind.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SiteTrustAttestationRequestV1 {
    /// Installation owning this one-use ceremony.
    pub installation_id: InstallationId,
    /// Enrolled physical iPhone expected to attest.
    pub device_id: DeviceId,
    /// Exact registered iPhone verification key expected to attest.
    pub key_id: KeyId,
    /// Independently generated non-zero ceremony identifier.
    pub ceremony_id: SiteTrustFactCeremonyIdV1,
    /// Exact frozen Proxenos canonical Site Trust payload.
    pub canonical_payload: SiteTrustCanonicalPayloadV1,
    /// Exact opaque Pistis intent from the Proxenos UDS contract.
    pub pistis_intent: SiteTrustPistisIntentV1,
    /// Host-recorded issuance time for durable audit evidence.
    pub issued_at: UnixTimeMillis,
}

impl SiteTrustAttestationRequestV1 {
    /// Validates cross-field request bindings before any verifier or store call.
    ///
    /// # Errors
    ///
    /// Returns a redacted failure when the all-zero ceremony ID or intent/payload
    /// binding is invalid.
    pub fn validate(&self) -> Result<(), SiteTrustFactIssuanceErrorV1> {
        if self.ceremony_id.is_zero_sentinel()
            || self.pistis_intent.reference() != self.canonical_payload.intent_reference()
        {
            return Err(SiteTrustFactIssuanceErrorV1::InvalidBinding);
        }
        Ok(())
    }

    /// Produces the exact domain-separated digest that App Attest must verify.
    #[must_use]
    pub fn verification_request(&self) -> SiteTrustAttestationVerificationRequestV1 {
        let digest = digest_components(
            ATTESTATION_CHALLENGE_DOMAIN_V1,
            [
                self.installation_id.as_bytes().as_slice(),
                self.device_id.as_bytes().as_slice(),
                self.key_id.as_bytes().as_slice(),
                self.ceremony_id.as_bytes().as_slice(),
                self.canonical_payload.canonical_bytes(),
                self.pistis_intent.as_str().as_bytes(),
                &self.issued_at.get().to_be_bytes(),
            ],
        );
        SiteTrustAttestationVerificationRequestV1 {
            installation_id: self.installation_id,
            device_id: self.device_id,
            key_id: self.key_id,
            ceremony_id: self.ceremony_id,
            canonical_payload_digest: *self.canonical_payload.digest(),
            pistis_intent: self.pistis_intent.clone(),
            challenge_digest: SiteTrustAttestationChallengeDigestV1(digest),
        }
    }
}

/// Non-secret verification inputs supplied to the Pistis-owned Apple verifier.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SiteTrustAttestationVerificationRequestV1 {
    /// Installation whose registered App Attest key must be checked.
    pub installation_id: InstallationId,
    /// Expected enrolled iPhone identity.
    pub device_id: DeviceId,
    /// Expected registered iPhone key identity.
    pub key_id: KeyId,
    /// One-use ceremony identity.
    pub ceremony_id: SiteTrustFactCeremonyIdV1,
    /// SHA-256 digest of the exact Proxenos canonical bytes.
    pub canonical_payload_digest: [u8; 32],
    /// Exact opaque Pistis intent string.
    pub pistis_intent: SiteTrustPistisIntentV1,
    /// Domain-separated digest that must be present in a verified App Attest assertion.
    pub challenge_digest: SiteTrustAttestationChallengeDigestV1,
}

/// Coarse result from validating an Apple App Attest assertion.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AttestationVerificationFailureV1 {
    /// No reviewed Apple trust-bundle verifier is available.
    Unavailable,
    /// The assertion is malformed, unauthentic, expired, or otherwise invalid.
    Invalid,
    /// The verified device or key does not match the exact ceremony request.
    BindingMismatch,
}

impl fmt::Display for AttestationVerificationFailureV1 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::Unavailable => "Apple App Attest verification is unavailable",
            Self::Invalid => "Apple App Attest verification failed",
            Self::BindingMismatch => "Apple App Attest binding did not match the ceremony",
        })
    }
}

impl std::error::Error for AttestationVerificationFailureV1 {}

/// A Pistis-owned verifier for Apple App Attest assertion bytes.
///
/// Only a reviewed implementation inside Pistis may mint the opaque verified
/// result.  Implementations must validate Apple's trust chain, app identity,
/// registered key, counter, and the exact `challenge_digest`; this public port
/// intentionally exposes no constructor for a verified result.
pub trait AppleAppAttestVerifierV1 {
    /// Verifies one bounded assertion against one exact request.
    ///
    /// # Errors
    ///
    /// Any unavailable trust bundle, malformed assertion, or binding mismatch
    /// must return an error and must never cause a fact to be recorded.
    fn verify(
        &self,
        request: &SiteTrustAttestationVerificationRequestV1,
        assertion: &AppleAppAttestAssertionV1,
    ) -> Result<VerifiedIPhoneAppAttestationV1, AttestationVerificationFailureV1>;
}

/// The only shipped Apple App Attest verifier until Apple trust-bundle validation exists.
#[derive(Clone, Copy, Debug, Default)]
pub struct UnavailableAppleAppAttestVerifierV1;

impl AppleAppAttestVerifierV1 for UnavailableAppleAppAttestVerifierV1 {
    fn verify(
        &self,
        _request: &SiteTrustAttestationVerificationRequestV1,
        _assertion: &AppleAppAttestAssertionV1,
    ) -> Result<VerifiedIPhoneAppAttestationV1, AttestationVerificationFailureV1> {
        Err(AttestationVerificationFailureV1::Unavailable)
    }
}

/// A non-secret durable fact issued only after a Pistis-owned verifier succeeds.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SiteTrustHumanAuthorityFactV1 {
    id: SiteTrustFactIdV1,
    installation_id: InstallationId,
    device_id: DeviceId,
    key_id: KeyId,
    ceremony_id: SiteTrustFactCeremonyIdV1,
    canonical_payload: SiteTrustCanonicalPayloadV1,
    pistis_intent: SiteTrustPistisIntentV1,
    issued_at: UnixTimeMillis,
    attestation_digest: [u8; 32],
}

impl SiteTrustHumanAuthorityFactV1 {
    /// Returns the exact versioned fact profile.
    #[must_use]
    pub const fn profile(&self) -> &'static str {
        SITE_TRUST_HUMAN_AUTHORITY_FACT_PROFILE_V1
    }

    /// Returns the stable fact identifier used for durable one-use consumption.
    #[must_use]
    pub const fn id(&self) -> SiteTrustFactIdV1 {
        self.id
    }

    /// Returns the installation bound to the verified fact.
    #[must_use]
    pub const fn installation_id(&self) -> InstallationId {
        self.installation_id
    }

    /// Returns the verified iPhone identity.
    #[must_use]
    pub const fn device_id(&self) -> DeviceId {
        self.device_id
    }

    /// Returns the verified iPhone key identity.
    #[must_use]
    pub const fn key_id(&self) -> KeyId {
        self.key_id
    }

    /// Returns the one-use ceremony identifier.
    #[must_use]
    pub const fn ceremony_id(&self) -> SiteTrustFactCeremonyIdV1 {
        self.ceremony_id
    }

    /// Returns the exact non-secret payload that Proxenos must revalidate.
    #[must_use]
    pub fn canonical_payload(&self) -> &SiteTrustCanonicalPayloadV1 {
        &self.canonical_payload
    }

    /// Returns the exact opaque Pistis intent wire value.
    #[must_use]
    pub fn pistis_intent(&self) -> &SiteTrustPistisIntentV1 {
        &self.pistis_intent
    }

    /// Returns the host-recorded fact issuance time.
    #[must_use]
    pub const fn issued_at(&self) -> UnixTimeMillis {
        self.issued_at
    }

    /// Returns only the digest of the verified App Attest assertion.
    #[must_use]
    pub const fn attestation_digest(&self) -> &[u8; 32] {
        &self.attestation_digest
    }

    /// Returns the exact atomic-consumption expectation for this fact.
    #[must_use]
    pub fn consumption_request(&self) -> SiteTrustFactConsumptionRequestV1 {
        SiteTrustFactConsumptionRequestV1 {
            id: self.id,
            installation_id: self.installation_id,
            device_id: self.device_id,
            key_id: self.key_id,
            ceremony_id: self.ceremony_id,
            canonical_payload_digest: *self.canonical_payload.digest(),
            pistis_intent: self.pistis_intent.clone(),
        }
    }
}

/// Exact expected bindings for atomic durable fact consumption.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SiteTrustFactConsumptionRequestV1 {
    /// Stable fact identifier.
    pub id: SiteTrustFactIdV1,
    /// Expected installation.
    pub installation_id: InstallationId,
    /// Expected iPhone device.
    pub device_id: DeviceId,
    /// Expected iPhone key.
    pub key_id: KeyId,
    /// Expected one-use ceremony identifier.
    pub ceremony_id: SiteTrustFactCeremonyIdV1,
    /// Expected exact canonical-payload digest.
    pub canonical_payload_digest: [u8; 32],
    /// Expected exact opaque Pistis intent.
    pub pistis_intent: SiteTrustPistisIntentV1,
}

/// A redacted outcome from atomic fact consumption.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SiteTrustFactConsumptionV1 {
    /// The durably consumed fact identifier.
    pub id: SiteTrustFactIdV1,
}

/// Failure from the host-owned durable fact transaction.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SiteTrustFactConsumptionErrorV1 {
    /// The fact or durable store is unavailable.
    Unavailable,
    /// Persisted data is corrupt, ambiguous, or violates the immutable fact contract.
    Corrupt,
    /// The fact was already consumed or conflicts with another one-use ceremony.
    Replayed,
    /// One expected installation, device, key, payload, intent, or ceremony binding differs.
    BindingMismatch,
}

impl fmt::Display for SiteTrustFactConsumptionErrorV1 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::Unavailable => "Site Trust fact store is unavailable",
            Self::Corrupt => "Site Trust fact store is corrupt",
            Self::Replayed => "Site Trust fact has already been consumed",
            Self::BindingMismatch => "Site Trust fact binding did not match",
        })
    }
}

impl std::error::Error for SiteTrustFactConsumptionErrorV1 {}

/// Monas-owned durable issuance and atomic single-use consumption boundary.
///
/// `record_verified` and `consume_exact` must be transactional durable
/// operations.  `consume_exact` must compare every field in
/// [`SiteTrustFactConsumptionRequestV1`], record the consumption/audit event,
/// and transition the fact to consumed in the same rollback-capable transaction.
/// It must not offer a read-then-consume compatibility sequence.
pub trait SiteTrustFactStoreV1 {
    /// Records one fact only after an Apple verifier returned a verified result.
    ///
    /// # Errors
    ///
    /// Duplicate ceremony IDs, unavailable durable state, or audit failures
    /// return a coarse error and must leave no partially issued fact.
    fn record_verified(
        &mut self,
        fact: SiteTrustHumanAuthorityFactV1,
    ) -> Result<(), SiteTrustFactConsumptionErrorV1>;

    /// Atomically compares and consumes one fact for the next Site Trust gate.
    ///
    /// # Errors
    ///
    /// A mismatch, replay, unavailable store, or audit failure must deny the
    /// gate without an authority fallback or a second consumption attempt.
    fn consume_exact(
        &mut self,
        request: SiteTrustFactConsumptionRequestV1,
    ) -> Result<SiteTrustFactConsumptionV1, SiteTrustFactConsumptionErrorV1>;
}

/// Failure while issuing a verified durable human-authority fact.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SiteTrustFactIssuanceErrorV1 {
    /// The request did not bind one non-zero ceremony and exact payload intent.
    InvalidBinding,
    /// Apple App Attest was unavailable, invalid, or bound to another device/key.
    Attestation(AttestationVerificationFailureV1),
    /// The Monas-owned durable fact transaction rejected issuance.
    Store(SiteTrustFactConsumptionErrorV1),
}

impl fmt::Display for SiteTrustFactIssuanceErrorV1 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidBinding => formatter.write_str("Site Trust fact binding is invalid"),
            Self::Attestation(error) => write!(formatter, "Site Trust attestation failed: {error}"),
            Self::Store(error) => write!(formatter, "Site Trust fact store failed: {error}"),
        }
    }
}

impl std::error::Error for SiteTrustFactIssuanceErrorV1 {}

/// Verifies an iPhone assertion and durably records a fact without retaining raw assertion bytes.
///
/// # Errors
///
/// A failed request validation or unavailable/invalid Apple verifier returns
/// before the store is touched.  A successful verifier result is still denied
/// if the exact device and key do not match the request.
pub fn issue_site_trust_human_authority_fact_v1(
    attestation_verifier: &impl AppleAppAttestVerifierV1,
    store: &mut impl SiteTrustFactStoreV1,
    request: SiteTrustAttestationRequestV1,
    assertion: &AppleAppAttestAssertionV1,
) -> Result<SiteTrustHumanAuthorityFactV1, SiteTrustFactIssuanceErrorV1> {
    request.validate()?;
    let verification_request = request.verification_request();
    let verified_result = attestation_verifier
        .verify(&verification_request, assertion)
        .map_err(SiteTrustFactIssuanceErrorV1::Attestation)?;
    if verified_result.device_id != request.device_id || verified_result.key_id != request.key_id {
        return Err(SiteTrustFactIssuanceErrorV1::Attestation(
            AttestationVerificationFailureV1::BindingMismatch,
        ));
    }
    issue_site_trust_human_authority_fact_from_verified_v1(store, request, verified_result)
}

/// Opaque successfully verified App Attest result.
///
/// There is deliberately no public constructor: unverified app input, a
/// browser, OS identity, or test fixture outside this module cannot mint it.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct VerifiedIPhoneAppAttestationV1 {
    device_id: DeviceId,
    key_id: KeyId,
    assertion_digest: [u8; 32],
}

impl VerifiedIPhoneAppAttestationV1 {
    pub(crate) fn from_verified_assertion_digest(
        device_id: DeviceId,
        key_id: KeyId,
        assertion_digest: [u8; 32],
    ) -> Self {
        Self {
            device_id,
            key_id,
            assertion_digest,
        }
    }

    #[cfg(test)]
    fn test_verified(device_id: DeviceId, key_id: KeyId, assertion: &[u8]) -> Self {
        Self {
            device_id,
            key_id,
            assertion_digest: Sha256::digest(assertion).into(),
        }
    }
}

fn parse_payload_fields(
    canonical_bytes: &[u8],
) -> Result<[String; FACT_PAYLOAD_FIELDS], SiteTrustCanonicalPayloadErrorV1> {
    let mut fields = Vec::with_capacity(FACT_PAYLOAD_FIELDS);
    let mut position = 0_usize;
    for expected_tag in 1..=u8::try_from(FACT_PAYLOAD_FIELDS).expect("fixed field count") {
        let Some(&tag) = canonical_bytes.get(position) else {
            return Err(SiteTrustCanonicalPayloadErrorV1::NonCanonical);
        };
        position += 1;
        if tag != expected_tag {
            return Err(SiteTrustCanonicalPayloadErrorV1::NonCanonical);
        }
        let Some(length_bytes) = canonical_bytes.get(position..position + 4) else {
            return Err(SiteTrustCanonicalPayloadErrorV1::NonCanonical);
        };
        position += 4;
        let length = usize::try_from(u32::from_be_bytes(
            length_bytes
                .try_into()
                .map_err(|_| SiteTrustCanonicalPayloadErrorV1::NonCanonical)?,
        ))
        .map_err(|_| SiteTrustCanonicalPayloadErrorV1::NonCanonical)?;
        if !(1..=MAXIMUM_PAYLOAD_FIELD_BYTES).contains(&length) {
            return Err(SiteTrustCanonicalPayloadErrorV1::InvalidField);
        }
        let Some(value) = canonical_bytes.get(position..position + length) else {
            return Err(SiteTrustCanonicalPayloadErrorV1::NonCanonical);
        };
        position += length;
        if !value.iter().all(|byte| (0x21..=0x7e).contains(byte)) {
            return Err(SiteTrustCanonicalPayloadErrorV1::InvalidField);
        }
        fields.push(
            String::from_utf8(value.to_vec())
                .map_err(|_| SiteTrustCanonicalPayloadErrorV1::InvalidField)?,
        );
    }
    if position != canonical_bytes.len() {
        return Err(SiteTrustCanonicalPayloadErrorV1::NonCanonical);
    }
    fields
        .try_into()
        .map_err(|_| SiteTrustCanonicalPayloadErrorV1::NonCanonical)
}

fn valid_intent_reference(value: &str) -> bool {
    value.starts_with("intent-")
        && value.len() <= MAXIMUM_INTENT_BYTES - PISTIS_INTENT_PREFIX_V1.len()
        && value
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'-')
}

fn contains_prohibited_material(value: &str) -> bool {
    [
        "pistis-",
        "credential",
        "private-key",
        "public-key",
        "token",
        "secret",
        "lease",
        "provider",
        "recovery",
    ]
    .iter()
    .any(|term| value.contains(term))
}

fn digest_components<const N: usize>(domain: &[u8], components: [&[u8]; N]) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update(domain);
    for component in components {
        let length = u32::try_from(component.len()).expect("all components are bounded");
        hasher.update(length.to_be_bytes());
        hasher.update(component);
    }
    hasher.finalize().into()
}

/// Isolated wholly in-process fixtures for sibling contract tests.
///
/// This module is compiled only for tests and cannot mint production evidence.
#[cfg(test)]
pub(crate) mod test_fixture;

#[cfg(test)]
mod tests {
    use super::*;

    fn payload(intent: &str) -> Vec<u8> {
        let fields = [
            PROXENOS_PAYLOAD_PROFILE_V1,
            "1",
            "request-pending",
            "site-00000001",
            "proxenos-local",
            "rev-00000001",
            "machine-000001",
            "monas-local",
            "trust-admission",
            "op-000000000001",
            "20260802T120000Z",
            "20260802T120500Z",
            intent,
        ];
        fields
            .iter()
            .enumerate()
            .fold(Vec::new(), |mut bytes, (index, value)| {
                bytes.push(u8::try_from(index + 1).expect("tag"));
                bytes.extend_from_slice(&u32::try_from(value.len()).expect("length").to_be_bytes());
                bytes.extend_from_slice(value.as_bytes());
                bytes
            })
    }

    fn request(intent: &str) -> SiteTrustAttestationRequestV1 {
        SiteTrustAttestationRequestV1 {
            installation_id: InstallationId::from_bytes([1; 16]),
            device_id: DeviceId::from_bytes([2; 16]),
            key_id: KeyId::from_bytes([3; 32]),
            ceremony_id: SiteTrustFactCeremonyIdV1::from_bytes([4; 16]),
            canonical_payload: SiteTrustCanonicalPayloadV1::parse(payload(intent))
                .expect("payload"),
            pistis_intent: SiteTrustPistisIntentV1::parse(format!(
                "{PISTIS_INTENT_PREFIX_V1}{intent}"
            ))
            .expect("intent"),
            issued_at: UnixTimeMillis::new(123),
        }
    }

    struct RecordingStore {
        fact: Option<SiteTrustHumanAuthorityFactV1>,
        consumed: bool,
    }

    impl RecordingStore {
        fn empty() -> Self {
            Self {
                fact: None,
                consumed: false,
            }
        }
    }

    impl SiteTrustFactStoreV1 for RecordingStore {
        fn record_verified(
            &mut self,
            fact: SiteTrustHumanAuthorityFactV1,
        ) -> Result<(), SiteTrustFactConsumptionErrorV1> {
            if self.fact.is_some() {
                return Err(SiteTrustFactConsumptionErrorV1::Replayed);
            }
            self.fact = Some(fact);
            Ok(())
        }

        fn consume_exact(
            &mut self,
            request: SiteTrustFactConsumptionRequestV1,
        ) -> Result<SiteTrustFactConsumptionV1, SiteTrustFactConsumptionErrorV1> {
            let Some(fact) = &self.fact else {
                return Err(SiteTrustFactConsumptionErrorV1::Unavailable);
            };
            if self.consumed {
                return Err(SiteTrustFactConsumptionErrorV1::Replayed);
            }
            if request != fact.consumption_request() {
                return Err(SiteTrustFactConsumptionErrorV1::BindingMismatch);
            }
            self.consumed = true;
            Ok(SiteTrustFactConsumptionV1 { id: fact.id() })
        }
    }

    struct TestVerifier;

    impl AppleAppAttestVerifierV1 for TestVerifier {
        fn verify(
            &self,
            request: &SiteTrustAttestationVerificationRequestV1,
            assertion: &AppleAppAttestAssertionV1,
        ) -> Result<VerifiedIPhoneAppAttestationV1, AttestationVerificationFailureV1> {
            if request.challenge_digest.as_bytes() == &[0; 32] {
                return Err(AttestationVerificationFailureV1::Invalid);
            }
            let device_id = if assertion.0.first() == Some(&0) {
                DeviceId::from_bytes([99; 16])
            } else {
                request.device_id
            };
            Ok(VerifiedIPhoneAppAttestationV1::test_verified(
                device_id,
                request.key_id,
                &assertion.0,
            ))
        }
    }

    #[test]
    fn unavailable_apple_verifier_never_records_a_fact() {
        let mut store = RecordingStore::empty();
        assert_eq!(
            issue_site_trust_human_authority_fact_v1(
                &UnavailableAppleAppAttestVerifierV1,
                &mut store,
                request("intent-000001"),
                &AppleAppAttestAssertionV1::parse(vec![9]).expect("assertion"),
            ),
            Err(SiteTrustFactIssuanceErrorV1::Attestation(
                AttestationVerificationFailureV1::Unavailable
            ))
        );
        assert!(store.fact.is_none());
        assert_eq!(
            issue_site_trust_human_authority_fact_v1(
                &TestVerifier,
                &mut store,
                request("intent-000001"),
                &AppleAppAttestAssertionV1::parse(vec![0]).expect("assertion"),
            ),
            Err(SiteTrustFactIssuanceErrorV1::Attestation(
                AttestationVerificationFailureV1::BindingMismatch
            ))
        );
        assert!(store.fact.is_none());
    }

    #[test]
    fn exact_payload_intent_and_one_use_consumption_are_bound() {
        let mut store = RecordingStore::empty();
        let fact = issue_site_trust_human_authority_fact_v1(
            &TestVerifier,
            &mut store,
            request("intent-000001"),
            &AppleAppAttestAssertionV1::parse(vec![9, 8, 7]).expect("assertion"),
        )
        .expect("verified test-only attestation");
        assert_eq!(fact.canonical_payload().site_id(), "site-00000001");
        assert_eq!(
            fact.pistis_intent().as_str(),
            "mnemosyne.pistis.intent.v1:intent-000001"
        );
        let consumption = fact.consumption_request();
        assert_eq!(
            store.consume_exact(consumption.clone()),
            Ok(SiteTrustFactConsumptionV1 { id: fact.id() })
        );
        assert_eq!(
            store.consume_exact(consumption),
            Err(SiteTrustFactConsumptionErrorV1::Replayed)
        );
    }

    #[test]
    fn mismatched_payload_intent_or_noncanonical_field_fails_before_verification() {
        let mut store = RecordingStore::empty();
        let mut invalid_payload = payload("intent-000001");
        invalid_payload[0] = 2;
        assert_eq!(
            SiteTrustCanonicalPayloadV1::parse(invalid_payload),
            Err(SiteTrustCanonicalPayloadErrorV1::NonCanonical)
        );
        let mut mismatched = request("intent-000001");
        mismatched.pistis_intent =
            SiteTrustPistisIntentV1::parse("mnemosyne.pistis.intent.v1:intent-000002".to_owned())
                .expect("intent");
        assert_eq!(
            issue_site_trust_human_authority_fact_v1(
                &TestVerifier,
                &mut store,
                mismatched,
                &AppleAppAttestAssertionV1::parse(vec![1]).expect("assertion"),
            ),
            Err(SiteTrustFactIssuanceErrorV1::InvalidBinding)
        );
        assert!(store.fact.is_none());
    }

    #[test]
    fn consumption_rejects_an_exactly_one_field_payload_substitution() {
        let mut store = RecordingStore::empty();
        let fact = issue_site_trust_human_authority_fact_v1(
            &TestVerifier,
            &mut store,
            request("intent-000001"),
            &AppleAppAttestAssertionV1::parse(vec![9]).expect("assertion"),
        )
        .expect("fact");
        let mut substituted = fact.consumption_request();
        substituted.canonical_payload_digest = [0; 32];
        assert_eq!(
            store.consume_exact(substituted),
            Err(SiteTrustFactConsumptionErrorV1::BindingMismatch)
        );
        assert!(!store.consumed);
    }
}
