use crate::{
    BindingExpectation, BindingResolver, CeremonyPurpose, Generation, IntegrationBlocker,
    ProductionReadiness,
};
use pistis_domain::{DeviceId, InstallationId, KeyId, UserId};
use pistis_identity::BindingId;
use pistis_protocol::UnixTimeMillis;

/// Independent, non-secret identifier correlating completion and audit.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct AuditCorrelationId([u8; 16]);

impl AuditCorrelationId {
    /// Constructs a correlation identifier from independently generated bytes.
    #[must_use]
    pub const fn from_bytes(bytes: [u8; 16]) -> Self {
        Self(bytes)
    }

    /// Returns the opaque bytes.
    #[must_use]
    pub const fn as_bytes(&self) -> &[u8; 16] {
        &self.0
    }
}

/// Digest of a host session identifier, never the session credential.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SessionIdDigest([u8; 32]);

impl SessionIdDigest {
    /// Constructs an audit-safe digest supplied by the host.
    #[must_use]
    pub const fn from_bytes(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }

    /// Returns the digest bytes.
    #[must_use]
    pub const fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }
}

/// Request for issuance by Synoptikon's sole session authority.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct HostSessionRequest {
    /// Existing local user to authenticate.
    pub user_id: UserId,
    /// Installation accepting the authentication.
    pub installation_id: InstallationId,
    /// Device that authenticated.
    pub device_id: DeviceId,
    /// Exact verification key used.
    pub key_id: KeyId,
    /// External identity binding slot.
    pub binding_id: BindingId,
    /// Authoritative authentication time.
    pub authenticated_at: UnixTimeMillis,
    /// Current policy generation.
    pub policy_generation: Generation,
    /// Current revocation generation.
    pub revocation_generation: Generation,
    /// Independent audit correlation identifier.
    pub correlation_id: AuditCorrelationId,
    /// Closed operation purpose; always ordinary session authentication.
    pub purpose: CeremonyPurpose,
}

impl HostSessionRequest {
    /// Constructs a request only after readiness and current bindings pass.
    ///
    /// The host must call this within the same transaction that consumes the
    /// challenge, invalidates pre-authentication state, issues its session, and
    /// appends audit evidence.
    ///
    /// # Errors
    ///
    /// Missing readiness evidence or any resolver failure blocks issuance.
    pub fn authorize(
        readiness: &ProductionReadiness,
        resolver: &impl BindingResolver,
        expected: BindingExpectation,
        authenticated_at: UnixTimeMillis,
        correlation_id: AuditCorrelationId,
    ) -> Result<Self, IntegrationBlocker> {
        readiness.require_ready()?;
        let authoritative_binding = resolver
            .resolve(expected)
            .map_err(IntegrationBlocker::Binding)?;
        authoritative_binding
            .validate(expected)
            .map_err(IntegrationBlocker::Binding)?;
        Ok(Self {
            user_id: authoritative_binding.user_id,
            installation_id: authoritative_binding.installation_id,
            device_id: authoritative_binding.device_id,
            key_id: authoritative_binding.key_id,
            binding_id: authoritative_binding.binding_id,
            authenticated_at,
            policy_generation: authoritative_binding.policy_generation,
            revocation_generation: authoritative_binding.revocation_generation,
            correlation_id,
            purpose: expected.purpose,
        })
    }
}

/// Outcome from the host's normal session authority.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct HostSessionOutcome {
    /// Audit-safe digest of the issued session identifier.
    pub session_id_digest: SessionIdDigest,
    /// Absolute session expiry.
    pub expires_at: UnixTimeMillis,
}

/// Host-owned session issuance boundary.
pub trait HostSessionIssuer {
    /// Issues a normal host session as one part of the completion transaction.
    ///
    /// No raw token or cookie crosses this contract.
    ///
    /// # Errors
    ///
    /// Any issuance, audit, or transaction failure must roll back completion.
    fn issue(&self, request: HostSessionRequest) -> Result<HostSessionOutcome, HostSessionError>;
}

/// Coarse host session failure safe to propagate across the adapter boundary.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum HostSessionError {
    /// Host persistence or session authority is unavailable.
    Unavailable,
    /// Transactional completion conflicted with concurrent state.
    Conflict,
    /// Central audit append failed and completion must roll back.
    AuditFailed,
}
